schema_version = 1

[project]
name = "Pinora_Template"
version = "0.1.0"

[paths]
firmware = "Firmware_Templates"
ui = "UI_Templates"
config = ".espConfig"

# [device]
# board = "esp32s3"
# port = "auto"
# baud_rate = 115200
