import { Unsigned32 } from "shared.slint";
import { Card } from "../components/card.slint";
import {  VerticalBox, HorizontalBox , Button } from "std-widgets.slint";
import { SliderCore } from "../components/SliderCore.slint";



export struct LedState {
    id: string,
    brightness: float,
}

 enum LedBrightness {
    off,
    on
 }

export global LedUpdates {
  
    in-out property <string> led-id;
    in-out property <LedState> led-state;
    in-out property <int> led-revision: 0;
    callback ledChanged(string , int);

    
}



export component LedView inherits Card {
    width: 350px;
    height: 180px;
    in property <string> module-id;
    private property <LedState> state;
    private property <int> update-revision: LedUpdates.led-revision;
    private property <LedBrightness> brightness: LedBrightness.off;

    changed update-revision => {
        if LedUpdates.led-id == root.module-id {
            root.state = LedUpdates.led-state;
            root.state.id = LedUpdates.led-id;
        }
    }
  

     VerticalBox {
        padding: 12px;
        VerticalBox {
            spacing: 3px;

            Text {
                text: "Remote Receiver";
                font-size: 19px;
                width: self.preferred-width;
                height: self.preferred-height;
            }
            Text {
                text: root.module-id;
                font-size: 10px;
                color: #88888892;
                                width: self.preferred-width;
                height: self.preferred-height;
            }
        }
        div := Rectangle{
            height: 1.2px;
            background: #88888892;
        }
        VerticalBox {
            padding: 10px;
            spacing: 10px;
            SliderCore {
                max: 100.0;
                min: 0.0;
                step: 1;
                value <=> state.brightness;
               valueChanged(newValue) => {
                    // Handle the value change here
                    // debug("Slider value changed to:", newValue);
                    LedUpdates.ledChanged(root.module-id, newValue);
                };

            }
            Button {
                text: (brightness == LedBrightness.on && state.brightness > 0)? "Off" : "On";
                width: self.preferred-width  + 7px;
                height: self.preferred-height + 7px;
              
                clicked => {
                    if brightness == LedBrightness.on {
                        state.brightness = 0;
                        LedUpdates.ledChanged(root.module-id, state.brightness);
                        brightness = LedBrightness.off;
                        return;
                    }
                    state.brightness = 100;
                    LedUpdates.ledChanged(root.module-id, state.brightness);
                    brightness = LedBrightness.on;
                };
            }
        }

       

    
    }
   
}

