export enum RemoteButton {
    None,
    Power,
    VolumeUp,
    FunctionStop,
    Previous,
    PlayPause,
    Next,
    Down,
    VolumeDown,
    Up,
    Zero,
    Equalizer,
    StopRepeat,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
}

export struct RemoteReceiverState {
    id: string,
    key: RemoteButton,
}

export global RemoteReceiverUpdates {
  
    in-out property <string> remote-receiver-id;
    in-out property <RemoteReceiverState> remote-receiver-state;
    in-out property <int> remote-receiver-revision: 0;
    callback remoteReceiverChanged(string);

    
}
