import {  VerticalBox  } from "std-widgets.slint";

export component SliderCore inherits Rectangle {
    in-out property <float> max : 100.0;
    in-out property <float> min : 0.0;
    in-out property <float> value : 0.0;
    in-out property <float> step: 1.0;
    in-out property <bool> piv : false;
    width: 300px;
    height: self.preferred-height;

    callback valueChanged(newValue: float);

    function  formattedValue() -> float {
        return  clampedValue().to-fixed(2).to-float();
    }

    function  normalizedValue() -> float {
        return (clampedValue() - min) / (max - min);
    }
    function  clampedValue() -> float {
        return Math.max(min, Math.min(max, value));
    }
    function  ispivot(width: float) -> float {
        if (piv) {
            return normalizedValue() * (width / 2);
        } else {
            return normalizedValue() * width;
        }
    }
    VerticalBox {
        padding: 2px;


        Text {
            text: formattedValue();
            font-size: 18px;
            x: parent.width / 2 - self.width / 2;
            vertical-alignment: center;
            horizontal-alignment: center;
            
        }

        HorizontalLayout{
            Text {
                text: min;
                font-size: 12px;
                vertical-alignment: center;
                color: #cfc1c18d;


            }
            Text {
                text: max;
                font-size: 12px;
                vertical-alignment: center;
                horizontal-alignment: end;
                color: #cfc1c18d;
            }
        }

        sk:= Rectangle {
            height: 8.6px;
            width: 100%;
            border-radius: 4px;

            background: gray;
            skCore := Rectangle {
                height: sk.height;
                border-radius: 4px;
                background: blue;
                x: piv
                ? Math.min(normalizedValue() * sk.width, sk.width / 2)
                : 0px;

                width: piv
                    ? Math.abs(normalizedValue() * sk.width - sk.width / 2)
                    : normalizedValue() * sk.width;
            }

            Rectangle {
                width: 20px;
                height: 20px;
                background: blue;
                border-radius: 6px;
               
                x: normalizedValue() * sk.width - self.width / 2;

                y: sk.height / 2 - self.height / 2;
            }


            touch := TouchArea {
                moved => {
                    if (self.pressed) {
                        root.value = root.min
                            + Math.max(
                                0.0,
                                Math.min(1.0, self.mouse-x / sk.width)
                            ) * (root.max - root.min);
                        root.valueChanged(formattedValue());
                    }
                }
            }

        }
       
    }
}
