import { VerticalBox , LineEdit } from "std-widgets.slint";
export component InputCore inherits VerticalBox {
    callback clicked();
    callback text-changed(string);
    in property <string> value: "";
    in property <string> placeholder: "";
    in property <string> label: "";
    in property <bool> disabled: false;

    spacing: 4px;
    width: 140px;
    height: 37px;

    Text {
        text: root.label;
        font-size: 15px;
        width: root.width;
       
    }

    LineEdit {
        width: root.width;
        height: 35px;
        text: root.value;
        placeholder-text: root.placeholder;
        enabled: !root.disabled;
        font-size: 18px;
        edited(text) => {
            root.text-changed(text);
        }
    }

}